apiVersion: apps/v1
kind: Deployment
metadata:
    name: second-app-deployment
spec:
    replicas: 1
    selector: 
        matchLabels:
            app: second-app
            tier: backend
    template: 
        metadata:
            labels:
                app: second-app #template name
                tier: backend
        spec:
            containers: 
                - name: second-node #container name
                  image: samyakinnovaccer/kuber-app:latest